create table if not exists districts
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50) NOT NULL,
    code       integer     NOT NULL,
    is_archive boolean
);

create table if not exists farmers (
                         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         organization_name varchar(255) NOT NULL,
                         legal_form varchar(10),
                         inn varchar(12) check (length(inn) between 10 and 12) NOT NULL,
                         kpp varchar(9) check (length(kpp::text)::int = 9),
                         ogrn varchar(15) check (length(ogrn) between 13 and 15),
                         registration_district_id int references districts(id),
                         registration_date date,
                         is_archived boolean
);

CREATE TABLE IF NOT EXISTS farmer_districts (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        farmer_id bigint references farmers(id),
                        district_id bigint references districts(id)
--                         primary key (farmer_id, district_id)
);

insert into districts (name, code, is_archive)
VALUES ('Barabinskiy', 101, false),
       ('Iskitimskiy', 201, false),
       ('Karasykskiy', 301, false),
       ('Kargatskiy', 401, false),
       ('Kolyvanskiy', 501, false),
       ('Kochenevskiy', 701, false),
       ('Moshkovskiy', 701, false),
       ('Ordynskiy', 701, false),
       ('Syzynskiy', 901, false);

insert into farmers (organization_name, legal_form, inn, kpp, ogrn, registration_district_id, registration_date, is_archived)
values ('Serp', 'FL', 1234567890, null, null, 2, '2023-04-05', false),
       ('Roga', 'YL', 123456789012, 463826475, 127384756574834, 3, '2024-04-05', false),
       ('Kopyta', 'IP', 123456789021, 564738475, 463759675647363, 5, '2021-04-05', false);

insert into farmer_districts (farmer_id, district_id)
values (1, 2),
       (1, 3),
       (1, 4),
       (2, 2),
       (2, 5),
       (3, 6),
       (3, 7),
       (3, 8);