create table if not exists districs
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50) NOT NULL,
    code       integer     NOT NULL,
    is_archive boolean
);

insert into districs (name, code, is_archive)
VALUES ('Барабинский', 101, false),
       ('Искитимский', 201, false),
       ('Карасукский', 301, false),
       ('Каргатский', 401, false),
       ('Колыванский', 501, false),
       ('Коченевский', 601, false),
       ('Мошковский', 701, false),
       ('Ордынский', 801, false),
       ('Сузунский', 901, false);