create table if not exists districts
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50) NOT NULL,
    code       integer     NOT NULL,
    is_archive boolean
);

insert into districts (name, code, is_archive)
VALUES ('Barabinskiy', 101, false),
       ('Iskitimskiy', 201, false),
       ('Karasykskiy', 301, false),
       ('Kargatskiy', 401, false),
       ('Kolyvanskiy', 501, false),
       ('Kochenevskiy', 601, false),
       ('Moshkovskiy', 701, false),
       ('Ordynskiy', 801, false),
       ('Syzynskiy', 901, false);