server:
  port: ${PORT:8081}

spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/registry}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
springdoc:
  swagger-ui:
    path: /swag.html
